# Site settings
title: Beard Meets Bread
header-img: img/home-bg.jpg
email: luke.tait@gmail.com
description: "I've made some bread, I have a beard, have a look!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  luketait
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
